voicepaw/so-vits-svc-fork

src/so_vits_svc_fork/__main__.py
- fixes logger not initialized in multiprocessing
=> fix: call init_logger()

src/so_vits_svc_fork/utils.py
=> fix: fix compute_f0_crepe returning wrong length

src/so_vits_svc_fork/inference/infer_tool.py, src/so_vits_svc_fork/inference_main.py, src/so_vits_svc_fork/utils.py
=> fix: fix RTF calculation

README.md
Co-authored-by: GarrettConway <gconway@g.hmc.edu>
=> docs(readme): update README.md regarding installation, update. WSL audio support

src/so_vits_svc_fork/gui.py, src/so_vits_svc_fork/utils.py
=> fix(gui): fix devices list and fix tqdm error in gui

src/so_vits_svc_fork/utils.py
Should fix #65 this time around.
The reason why this didn't work before is because it sorted them based on their name or time alone, but not also based on their prefix, so the resulting array looked like "G_", "D_", "G_", "D_", ...
This addresses that by also sorting based on their prefix, resulting in a properly sorted array "G_", "G_", "G_", "D_", "D_", "D_"
This has to be done this way due to how the itertools.groupby method works: https://note.nkmk.me/en/python-itertools-groupby/
Edit: Started training a new model from scratch with these code-changes, it's clearing it correctly
=> Fix old checkpoint deletion by sorting the models properly

src/so_vits_svc_fork/data_utils.py, src/so_vits_svc_fork/preprocess_flist_config.py
In an attempt to cut down on noise introduced by int16 wav quantization, I wanted to try using float32 wav files instead.
I found that python's wave library does not understand float32, so I removed the wave library based duration code for librosa's get_duration function instead.
I was also getting a `WavFileWarning: Chunk (non-data) not understood, skipping it.` message from scipy.io.wavfile.read. I noticed that the load_wav_to_torch() function + the normalization and unsqueeze, results in the exact same format as a simple torchaudio.load(), so this code has been simplified as well.
=> fix(data_utils): allow float32 audio to be processed properly

src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/preprocess_resample.py, src/so_vits_svc_fork/preprocess_speaker_diarization.py, src/so_vits_svc_fork/preprocess_split.py
=> fix(preprocess): fix dtype in sf.read() to save memory

src/so_vits_svc_fork/__init__.py, src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/gui.py, src/so_vits_svc_fork/logger.py, src/so_vits_svc_fork/utils.py
Another attempt at #104 
I've moved the logging intialisation into it's own file `logger.py`
Then inside `__init__.py` I'm importing it and calling the method
I had to move out the version and debug prints into the main file or otherwise they would be printed on every sub-process creation
Running the following 2 commands yields these results:
```
python -c "import so_vits_svc_fork.__main__;from logging import getLogger;getLogger().info('hello')"
python -c "import so_vits_svc_fork.train;from logging import getLogger;getLogger().info('hello')"
```
=> fix(logging): initialize logging in logger file and move version log

README.md
Tiniest change to add that video tutorial link.
would address: https://github.com/34j/so-vits-svc-fork/issues/138
=> docs(readme): add yt tutorial vid link

src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/preprocess_speaker_diarization.py, src/so_vits_svc_fork/preprocess_split.py, tests/test_main.py
=> fix(__main__): fix -h option overridden

src/so_vits_svc_fork/utils.py
After doing some profiling I found that repeat_expand_2d is relatively slow. Rather than manually repeating the array, take advantage of torch.nn.functional.interpolate which is a couple orders of magnitude faster.
I have tested the new and old methods and found the results to be the same.
=> perf(utils): better implementation of repeat_expand_2d

src/so_vits_svc_fork/inference/core.py
Nothing every actually sets RealtimeVC.split to False so this section of code goes unused, but this piece of code has a potential leak issue. If the audio is quiet enough to be considered silence, it just pumps the original audio through instead of outputting true silence. If this happens to be a silence misdetection then you possible leak the users' original voice.
=> fix: remove possible leak in unused code

src/so_vits_svc_fork/data_utils.py, src/so_vits_svc_fork/modules/mel_processing.py, src/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py, src/so_vits_svc_fork/train.py, src/so_vits_svc_fork/utils.py
=> perf: move methods from dataloader to pre-hubert

src/so_vits_svc_fork/train.py
=> fix(train): fix checkpoint not properly loaded

src/so_vits_svc_fork/train.py
This PR includes several things discussed in #270 
- It ensures the `_temp_epoch` variable is initialized in the LightningModule's `__init__` method (thanks @ne0escape)
- It moves the `__init__` method of the LightningModule to the top (bit of cleanup)
- It fixes the order of optimization done to the model as per the Lightning.AI documentation ([lightning.ai/docs/pytorch/stable/common/optimization.html#id2](https://lightning.ai/docs/pytorch/stable/common/optimization.html#id2))
- It removes a `with torch.no_grad():` call for the generator loss calculation which ends up vastly improving the quality of the model (less metallic noise during several tests with a model from scratch)
- It fixes the `log_audio_dict` function so it use the correct `total_batch_idx` value
- It fixes checkpoints …
=> fix(train): improve quality of training

src/so_vits_svc_fork/train.py
Since we're using manual optimization, we need to call `step()` on each of the learning rate schedulers.
This steps learning rates once per epoch so as to match the behavior before the lightning rewrite.
Relevant docs: https://lightning.ai/docs/pytorch/stable/common/optimization.html#learning-rate-scheduling
Closes #292
=> fix(train): fix lr_decay not working

src/so_vits_svc_fork/train.py
Add an optional `accumulate_grad_batches` param to the `train` part of the config to allow for gradient accumulation. ([Lightning docs](https://lightning.ai/docs/pytorch/stable/common/optimization.html#gradient-accumulation))
This updates the gradients once every `accumulate_grad_batches` batches, with a default value of 1 to not break any existing configs.
I went with the same name (`accumulate_grad_batches`) as the [argument to `Trainer`](https://lightning.ai/docs/pytorch/stable/common/trainer.html#accumulate-grad-batches), even though we're not actually using that argument due to doing manual optimization. I realize that might be confusing, so I'm open to suggestions.
I'm relatively new to ML/AI work, so just to double-check my understanding:
- `manual_backward` backpropagates and …
=> feat(train): add optional `accumulate_grad_batches` config param

src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/train.py
=> perf(train): specify num_workers in DataLoader

src/so_vits_svc_fork/train.py
Performing back propagation pass is what creates gradients. If the gradient logging calls are before manual_backward, then they will be logging the gradients of the previous step. Gradient clipping isn't actually performed but if it was, it should also have been done after gradients are created, but before the optimizer uses them.
This simply moves it into the right spot as it was in v3.0.5
https://github.com/34j/so-vits-svc-fork/blob/v3.0.5/src/so_vits_svc_fork/train.py#L278
=> fix(train): fix gradient logging

poetry.lock, pyproject.toml, src/so_vits_svc_fork/cluster/__init__.py, src/so_vits_svc_fork/cluster/train_cluster.py, src/so_vits_svc_fork/dataset.py, src/so_vits_svc_fork/preprocessing/preprocess_flist_config.py, src/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py, src/so_vits_svc_fork/preprocessing/preprocess_resample.py, src/so_vits_svc_fork/utils.py
=> fix: fix torch.load and save to use file objects to allow non-ASCII characters and use weights_only and remove unidecode

src/so_vits_svc_fork/preprocessing/config_templates/quickvc.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1-legacy.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1.json, src/so_vits_svc_fork/train.py
Closes #319 
By default it will use `version_0` and append new logs to that instead of making new ones.
This can be overriden by the user in the config through the `train.log_version` parameter.
=> feat(train): add TensorBoardLogger version parameter support

src/so_vits_svc_fork/train.py
It seems the `is_notebook` check was inverted here, which causes the fancy RichProgressBar to not show up locally (or in that case, actually supported places)
This might also fix #321
=> fix(train): fix check for notebook / Colab

src/so_vits_svc_fork/logger.py
As per this issue in the pytorch repository:
https://github.com/pytorch/pytorch/issues/97207
It seems a fix was already included which makes it only log once for the session, instead of every time it's being accessed.
Since this is out of our control as we aren't using any `.storage` (or specifically `TypedStorage`) methods directly I feel it's okay to suppress those warnings.
Closes #330
=> fix(train): suppress pytorch logs for deprecated TypedStorage

src/so_vits_svc_fork/train.py
With the addition of the `on_train_end` hook in 3.10.2 the checkpoints are now being saved when running auto batch size finding.
This PR adds a check for `self.tuning` and will not be saving checkpoints if it's true.
=> fix(train): don't save model when tuning for auto batch size

easy-installation/install.bat
So when we run the [install.bat],if the CUDA or CUDNN haven't installed, the bat will just disappeared and will not show anything, it is very confusing.like https://github.com/34j/so-vits-svc-fork/issues/374
To see the error messages, We need to run .bat from a console windows,This is very unfriendly to the beginner.So I replaced "exit" with "pause”.
Also, the “pause” gives user an option to force continue the installation process if the installer can’t correctly identified the CUDA or CUDNN which is install correctly.
=> chore(easy-installation): replace exit with pause

src/so_vits_svc_fork/gui.py
Closes #452
Implements:
- Output file box
- Auto incrementing default output path
=> feat(gui): configurable output file name

easy-installation/install-cn.bat
1.Following https://github.com/voicepaw/so-vits-svc-fork/pull/406 ，replace exit with pause and I add more pause，After requirement has been installed , it’ll be paused automatically. Users can manually check whether the pack is installed to avoid installation failure and opening svcg directly(which also cause the crash bug)
2.Translate all echoes into Chinese to make the experience more convenient for Chinese users. 
3.Replace pytorch mirror repositories for mainland China (TUNA mirror, SJTU mirror), so that users in mainland China can download them at normal speed instead of low speed or disconnecting the server. 
4.Add newlines and optimize the layout.
=> chore(easy-installation): add .BAT for Chinese

src/so_vits_svc_fork/modules/decoders/f0.py
Prevents the f0 decoder from modifying the speaker embeddings when lf0 loss is minimized.  Not sure how much this matters - I would appreciate feedback if anyone notices a difference in training.
=> fix(train): decouple lf0 predictor from speaker embeddings

src/so_vits_svc_fork/utils.py
It seems there was a typo/mistake in the checkpoint save/load functions, and the variable was called `iteration` instead of `epoch`, and the same typo is present in the save/load log messages, which was confusing to users.
As you can see in code below, we're actually passing `current_epoch` into save function.
https://github.com/voicepaw/so-vits-svc-fork/blob/ed3240a15e8c2584f2ec7e47df89f70ef6ee2920/src/so_vits_svc_fork/train.py#L275-L290
I fixed that typo, but left it as an `iteration` in the actual torch data structure to maintain backward compatibility with existing checkpoint files for this model.
=> fix(utils): fix epoch variable name in checkpoint save/load functions

src/so_vits_svc_fork/utils.py
The file that is about to be deleted is overwritten with a size of 0 bytes, this prevents trash overflow in google drive
Closes #474
=> fix(utils): complete removal of ckpts in colab

src/so_vits_svc_fork/inference/main.py
I found this work around as it is a problem with the libraries and librosa.
The PR changes main.py and converts the paths to a string. It shouldn't harm any other OS or cause issues.
=> fix(inference): pass str instead of Path in sf.load() and sf.write()

src/so_vits_svc_fork/inference/core.py, src/so_vits_svc_fork/utils.py
Added code to remove weight norms from `hubert` and `net_g` (inference only for `net_g`), because at least as of now (PyTorch 2.0.1), the `mps` backend in pytorch does not support weight norm.
=> fix(inference): remove weight norm on inference so `mps` backend will work without CPU fallback

notebooks/so-vits-svc-fork-4.0.ipynb
Changes:
- Added "import" for configs files
- Added backing up of the config file if you accidentaly override it
- Changed "clone" to export for configs files
Made that you can also import the configs files from Google Drive because it takes long if you have to do it every time to copy paste the files.
The Pull Request Fixes #1063
=> chore(notebook):  copy configs files from Google Drive

src/so_vits_svc_fork/preprocessing/preprocess_speaker_diarization.py
Fix #1156 
Set speaker-diarization version to 3.1 for pyannote.audio 3.1.1 compatibility. Ensure compatibility with torch 2.2.2+cu121 as well.
=> fix(pre-sd): set speaker-diarization version to 3.1 for pyannote.audio 3.1.1 compatibility

README.md, src/so_vits_svc_fork/gui.py
Hi, this is simple README.md edit just to update CIVITAI Link.
The old link no longer works for quite sometime, and this small README.md update use correct CIVITAI Link.
CIVITAI has tag for `so-vits-svc-fork` which is contain 15 model compared with just `so-vits-svc` (10 model)
Thank You
=> docs(readme): update CIVITAI Model URL
