voicepaw/so-vits-svc-fork

src/so_vits_svc_fork/gui.py
=> fix: use librosa.load() instead of soundfile.read()

src/so_vits_svc_fork/utils.py
=> fix(utils): fix latest_checkpoint_path

src/so_vits_svc_fork/utils.py
=> fix: fix clean_checkpoints

src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/default_gui_presets.json, src/so_vits_svc_fork/gui.py
=> fix(gui): fix speaker and devices not updated and fix defult presets

src/so_vits_svc_fork/inference/infer_tool.py
=> fix(infer_tool): fix speaker not automaticlly set to the first one if not found in cluster inference

src/so_vits_svc_fork/gui.py, src/so_vits_svc_fork/preprocess_resample.py, src/so_vits_svc_fork/preprocess_split.py
=> fix: fix audio resampled to 22kHz

tests/test_main.py
=> test: set n_jobs to 1 if ci

README_zh_CN.md
Update the Chinese documentation for the convenience of Chinese people
=> docs(readme_zh_cn): update README_zh_CN.md

src/so_vits_svc_fork/gui.py
=> fix(gui): fix wrong devices set as default

src/so_vits_svc_fork/preprocessing/config_templates/quickvc.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1-legacy.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1.json, src/so_vits_svc_fork/preprocessing/preprocess_hubert_f0.py, src/so_vits_svc_fork/utils.py
Closes #220, Closes #231, Closes #234, Closes #219
=> fix: fix issues when loading legacy checkpoint and fix pre-hubert n_jobs

src/so_vits_svc_fork/cluster/train_cluster.py
=> fix(cluster): fix train_cluster

src/so_vits_svc_fork/preprocessing/config_templates/quickvc.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1-legacy.json, src/so_vits_svc_fork/preprocessing/config_templates/so-vits-svc-4.0v1.json
https://github.com/34j/so-vits-svc-fork/issues/231#issuecomment-1497433011
=> chore(config_template): adjust batch_sizes again

poetry.lock, pyproject.toml, tests/test_main.py
=> fix: fix fastapi version to 0.88

README.md, README_zh_CN.md
=> fix(readme): fix wrong commands in "Before training"

src/so_vits_svc_fork/logger.py
=> fix(logger): fix init_logger not showing debug messages in certain conditions as intended

src/so_vits_svc_fork/train.py
=> fix(train): fix ddp not working

src/so_vits_svc_fork/train.py
As per the Lightning.AI documentation here:
https://lightning.ai/docs/pytorch/stable/common/progress_bar.html#richprogressbar
We could even customize it, but I haven't dug too deep into it.
Closes #308
=> feat(train): use RichProgressBar

src/so_vits_svc_fork/gui.py
This PR will change the "Infer" button to run in a thread utilizing PySimpleGui's `window.start_thread` method.
While this is going on, the "Infer" button will be disabled until inference is completed (or fails due to an exception)
This will prevent the GUI from freezing up and will allow the user to already prepare the settings for the next inference
___
Added another commit fixing the "Infer" button from disabling a bit too late, potentially making it possible to quickly run it multiple times in a row (e.g. spam clicking)
=> feat(gui): run inference in a separate process and temporarily disable button

src/so_vits_svc_fork/train.py, src/so_vits_svc_fork/utils.py
=> fix: patch stft and add mps to get_optimal_device()

src/so_vits_svc_fork/cluster/__init__.py
=> fix(cluster): do not use weights_only in get_cluster_model()

src/so_vits_svc_fork/gui.py
=> fix(gui): fix subprocess errors in linux and fix wrong error logging

src/so_vits_svc_fork/gui.py
=> fix(gui): always use "spawn" context in ProcessPool

src/so_vits_svc_fork/__main__.py, src/so_vits_svc_fork/gui.py, src/so_vits_svc_fork/logger.py, src/so_vits_svc_fork/train.py, src/so_vits_svc_fork/utils.py
Closes #295, Closes #359, Closes #375, Closes #380
=> fix(train): set persistent_workers = True in DataLoader for performance, do not save checkpoints, fix logging issue and multiple warning issues

src/so_vits_svc_fork/train.py
=> fix(train): support ddp in Windows (gloo backend)

src/so_vits_svc_fork/train.py
Additionally, turn saving checkpoints code into it's own function and call it for both `on_validation_end` as well as `on_train_end` so that it will save checkpoints after the training ends
Fixes #399 and #350 
Small explanation for `self.trainer.sanity_checking`:
This is set to `true` when the initial validation steps are being run before training begins.
=> fix(train): properly stop training after `epochs` has been reached

src/so_vits_svc_fork/train.py, src/so_vits_svc_fork/utils.py
This should resolve #415 and #447.
=> fix(train): only save checkpoints on main device

src/so_vits_svc_fork/utils.py
=> fix(utils): fix so-vits-svc style contentvec usage

README.md
=> docs(readme): fix typo in README.md

src/so_vits_svc_fork/dataset.py, src/so_vits_svc_fork/gui.py, src/so_vits_svc_fork/preprocessing/preprocess_flist_config.py, src/so_vits_svc_fork/utils.py, tests/test_main.py
=> fix: specify encoding to utf-8 in read_text() and write_text()

src/so_vits_svc_fork/logger.py
=> fix(logger): remove FileHandler to avoid PermissionError

easy-installation/install.bat
=> chore(easy-installation): enclose paths with double quotes

src/so_vits_svc_fork/gui.py
=> fix(gui): always refresh output path if input path changed

src/so_vits_svc_fork/__main__.py
gui has relative modules, so being able to enter from __main__ would streamline debugger launching.
=> feat(main/cli): add gui command for module root entrypoint

src/so_vits_svc_fork/inference/core.py
fixed a typo in the word "infereNce"
=> fix(inference): fix typo in core.py

poetry.lock, pyproject.toml
Reverts voicepaw/so-vits-svc-fork#952
=> revert(deps): revert "fix(deps): update python to >=3.11,<3.12"

src/so_vits_svc_fork/modules/decoders/mb_istft/_pqmf.py
importing `kaiser` from scipy.signal.windows
Closes #1138
=> fix(pqmf): fix broken  scipy imports in _pqmf.py

src/so_vits_svc_fork/preprocessing/preprocess_speaker_diarization.py
Fixes #1154 
Add leading zeros for 4-digit fixed width of the output file name's numeric part.
=> feat(pre-sd): add leading zeros for 4-digit width of the output file name's numeric part

src/so_vits_svc_fork/gui.py
Add a basic platform check.
Closes #602
=> fix(gui): fix format selection for the input audio in non-Windows
